//! Persistence contract for published schemas and shared instances.

use async_trait::async_trait;
use serde_json::{Map, Value};
use uuid::Uuid;

use crate::{
    LinkId, LinkTypeId, ObjectId, ObjectTypeId, OntologyError, RevisionId, SchemaDocument, TagName,
};

/// A published immutable schema revision.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PublishedRevision {
    /// Content-addressed revision identity.
    pub id: RevisionId,
    /// Validated schema body stored for this revision.
    pub schema: SchemaDocument,
}

/// A stored object instance.
#[derive(Debug, Clone, PartialEq)]
pub struct ObjectRecord {
    /// Internal instance identity.
    pub id: ObjectId,
    /// The schema object type identity.
    pub object_type_id: ObjectTypeId,
    /// Complete object values document.
    pub values: Map<String, Value>,
    /// Optimistic concurrency version.
    pub version: u64,
}

/// Data required to create an object instance.
#[derive(Debug, Clone, PartialEq)]
pub struct NewObjectRecord {
    /// Internal instance identity generated by the service.
    pub id: ObjectId,
    /// The schema object type identity.
    pub object_type_id: ObjectTypeId,
    /// Complete object values document.
    pub values: Map<String, Value>,
}

/// A stored directed link instance.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LinkRecord {
    /// Internal instance identity.
    pub id: LinkId,
    /// The schema link type identity.
    pub link_type_id: LinkTypeId,
    /// Source object identity.
    pub source_object_id: ObjectId,
    /// Target object identity.
    pub target_object_id: ObjectId,
    /// Optimistic concurrency version.
    pub version: u64,
}

/// Data required to create a link instance.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NewLinkRecord {
    /// Internal instance identity generated by the service.
    pub id: LinkId,
    /// The schema link type identity.
    pub link_type_id: LinkTypeId,
    /// Source object identity.
    pub source_object_id: ObjectId,
    /// Target object identity.
    pub target_object_id: ObjectId,
}

/// A consistent repository view used to validate a schema against shared instances.
#[derive(Debug, Clone, PartialEq)]
pub struct SchemaValidationSnapshot {
    /// All objects visible in the validation view.
    pub objects: Vec<ObjectRecord>,
    /// All links visible in the same validation view.
    pub links: Vec<LinkRecord>,
}

/// One cursor page of stored records.
#[derive(Debug, Clone, PartialEq)]
pub struct Page<T> {
    /// Records returned for the requested page.
    pub items: Vec<T>,
    /// Cursor to pass as `after` for the following page.
    pub next_after: Option<Uuid>,
}

/// Storage operations required by the ontology service.
#[async_trait]
pub trait OntologyRepository: Send + Sync {
    /// Inserts an immutable published revision idempotently.
    ///
    /// # Errors
    ///
    /// Returns an ontology error when persistence fails.
    async fn insert_revision(&self, revision: PublishedRevision) -> Result<(), OntologyError>;

    /// Loads a revision by its content identity.
    ///
    /// # Errors
    ///
    /// Returns an ontology error when persistence fails.
    async fn get_revision(
        &self,
        id: &RevisionId,
    ) -> Result<Option<PublishedRevision>, OntologyError>;

    /// Lists every published revision.
    ///
    /// # Errors
    ///
    /// Returns an ontology error when persistence fails.
    async fn list_revisions(&self) -> Result<Vec<PublishedRevision>, OntologyError>;

    /// Creates or moves a tag to a published revision.
    ///
    /// # Errors
    ///
    /// Returns an ontology error when persistence fails.
    async fn put_tag(&self, name: &TagName, revision_id: &RevisionId) -> Result<(), OntologyError>;

    /// Resolves a tag to its revision identity.
    ///
    /// # Errors
    ///
    /// Returns an ontology error when persistence fails.
    async fn get_tag(&self, name: &TagName) -> Result<Option<RevisionId>, OntologyError>;

    /// Deletes a tag.
    ///
    /// # Errors
    ///
    /// Returns an ontology error when persistence fails.
    async fn delete_tag(&self, name: &TagName) -> Result<(), OntologyError>;

    /// Reads all shared instances from one consistent validation view.
    ///
    /// Implementations must obtain both collections from the same snapshot; a
    /// database backend can use one repeatable-read transaction for this method.
    ///
    /// # Errors
    ///
    /// Returns an ontology error when persistence fails.
    async fn schema_validation_snapshot(&self) -> Result<SchemaValidationSnapshot, OntologyError>;

    /// Persists a new object.
    ///
    /// # Errors
    ///
    /// Returns an ontology error when persistence fails.
    async fn create_object(&self, object: NewObjectRecord) -> Result<ObjectRecord, OntologyError>;

    /// Loads an object by identity.
    ///
    /// # Errors
    ///
    /// Returns an ontology error when persistence fails.
    async fn get_object(&self, id: ObjectId) -> Result<Option<ObjectRecord>, OntologyError>;

    /// Returns one object type page after an optional object cursor.
    ///
    /// # Errors
    ///
    /// Returns an ontology error when persistence fails.
    async fn page_objects(
        &self,
        type_id: ObjectTypeId,
        after: Option<ObjectId>,
        limit: u32,
    ) -> Result<Page<ObjectRecord>, OntologyError>;

    /// Replaces an object conditionally on its version.
    ///
    /// # Errors
    ///
    /// Returns an ontology error when persistence fails.
    async fn replace_object(&self, object: ObjectRecord) -> Result<ObjectRecord, OntologyError>;

    /// Deletes an object, optionally deleting its links too.
    ///
    /// # Errors
    ///
    /// Returns an ontology error when persistence fails.
    async fn delete_object(
        &self,
        id: ObjectId,
        version: u64,
        force: bool,
    ) -> Result<(), OntologyError>;

    /// Persists a new link.
    ///
    /// # Errors
    ///
    /// Returns an ontology error when persistence fails.
    async fn create_link(&self, link: NewLinkRecord) -> Result<LinkRecord, OntologyError>;

    /// Loads a link by identity.
    ///
    /// # Errors
    ///
    /// Returns an ontology error when persistence fails.
    async fn get_link(&self, id: LinkId) -> Result<Option<LinkRecord>, OntologyError>;

    /// Returns one link page after an optional link cursor.
    ///
    /// # Errors
    ///
    /// Returns an ontology error when persistence fails.
    async fn page_links(
        &self,
        after: Option<LinkId>,
        limit: u32,
    ) -> Result<Page<LinkRecord>, OntologyError>;

    /// Replaces a link conditionally on its version.
    ///
    /// # Errors
    ///
    /// Returns an ontology error when persistence fails.
    async fn replace_link(&self, link: LinkRecord) -> Result<LinkRecord, OntologyError>;

    /// Deletes a link conditionally on its version.
    ///
    /// # Errors
    ///
    /// Returns an ontology error when persistence fails.
    async fn delete_link(&self, id: LinkId, version: u64) -> Result<(), OntologyError>;

    /// Lists relevant links while checking cardinality.
    ///
    /// # Errors
    ///
    /// Returns an ontology error when persistence fails.
    async fn links_for_cardinality(
        &self,
        type_id: LinkTypeId,
        source: ObjectId,
        target: ObjectId,
        excluding: Option<LinkId>,
    ) -> Result<Vec<LinkRecord>, OntologyError>;
}
